CREATE TABLE USUARIO1 (
ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
NOME NVARCHAR(200),
EMAIL NVARCHAR (150),
TELEFONE NVARCHAR(50),
ENDERECO NVARCHAR(150)
)

CREATE TABLE AUTOR1 (
ID_AUTOR INT PRIMARY KEY IDENTITY(1,1),
NOME NVARCHAR (200),
NACIONALIDADE NVARCHAR(100)
)

CREATE TABLE LIVRO1(
ID_LIVRO INT PRIMARY KEY IDENTITY(1,1),
TITULO NVARCHAR (200),
EDITORA NVARCHAR(200),
ANO_PUBLICACAO INT,
STS NVARCHAR(100)
)

CREATE TABLE EDITORA1(
ID_EDITORA INT PRIMARY KEY IDENTITY(1,1),
NOME NVARCHAR(200)
)

CREATE TABLE EMPRESTIMO1 (
ID_EMPRESTIMO INT PRIMARY KEY IDENTITY(1,1),
DATA_EMPRETIMO DATE,
DATA_DEVOLUCAO DATE,
DATA_PREV_DEVOLUCAO DATE,
ID_USUARIO INT,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO1(ID_USUARIO)
)

CREATE TABLE LIVRO_AUTOR1(
ID_LIVRO_AUTOR INT PRIMARY KEY IDENTITY(1,1),
ID_LIVRO INT,
ID_AUTOR INT,
FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO1(ID_LIVRO),
FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR1(ID_AUTOR)
)

CREATE TABLE EMPRESTIMO_LIVRO1(
ID_EMPRESTIMO_LIVRO INT PRIMARY KEY IDENTITY(1,1),
ID_LIVRO INT,
ID_EMPRESTIMO INT,
FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO1(ID_LIVRO),
FOREIGN KEY (ID_EMPRESTIMO) REFERENCES EMPRESTIMO1(ID_EMPRESTIMO)
)

CREATE TABLE MULTA1 (
ID_MULTA INT PRIMARY KEY IDENTITY(1,1),
VALOR DECIMAL(10,2),
ID_EMPRESTIMO INT,
DATA_PAGAMENTO DATE,
FOREIGN KEY (ID_EMPRESTIMO) REFERENCES EMPRESTIMO1(ID_EMPRESTIMO)
)

INSERT INTO USUARIO1 (NOME,EMAIL,TELEFONE,ENDERECO) VALUES 
('REGINALDO LOPES','reginaldo123@gmail.com','12991998303','RUA CRUZEIRO'),
('LARISSA CORDEIRO','larissa234@gmail.com','12992988402','RUA LORENA')
INSERT INTO USUARIO1 (NOME,EMAIL,TELEFONE,ENDERECO) VALUES 
('SARAH NUNES','sarahnunes@hotmail','12981385388','RUA APARECIDA'),
('LUIZ FELIPE','luizf12@gmail.com','12981007920','RUA GUARA')

SELECT * FROM USUARIO1

INSERT INTO USUARIO1 (NOME,EMAIL,TELEFONE,ENDERECO) VALUES 
('JOAO SILVA','joao123@gmail.com','1291923949','RUA ANTONIO BRASIL')

INSERT INTO AUTOR1 (NOME, NACIONALIDADE) VALUES
('MACHADO DE ASSIS','BRASILEIRO'),
('JULIA QUINN','AMERICANA'),
('JORGE AMADO','BRASILEIRO')

INSERT INTO AUTOR1 (NOME, NACIONALIDADE) VALUES
('JORGE COELHO','BRASILEIRO'),
('MARIA SILVA','AMERICANA')


SELECT * FROM AUTOR1

INSERT INTO LIVRO1(TITULO,EDITORA,ANO_PUBLICACAO,STS) VALUES
('DOM CASMURRO','LETRAS',1998,'DISPONIVEL'),
('BRIDGERTON','ARQUEIRO',2006,'DISPONIVEL'),
('CAPITAES DE AREA','LETRAS',1937,'INDISPONIVEL'),
('PODER DO HABITO','OBJETIVA',2005,'INDISPONIVEL'),
('O ALQUIMISTA','OBJETIVA',2000,'DIPONIVEL')

SELECT * FROM LIVRO1

INSERT INTO LIVRO_AUTOR1 (ID_LIVRO,ID_AUTOR) VALUES
(1,1),(3,3),(4,5),(5,4),(2,2)

SELECT * FROM LIVRO_AUTOR1


INSERT INTO EMPRESTIMO1 (DATA_EMPRETIMO,DATA_DEVOLUCAO,DATA_PREV_DEVOLUCAO,ID_USUARIO)  VALUES
('2026-04-01','2026-04-10','2026-04-08',1),
('2026-04-03','2026-04-15','2026-04-12',3),
('2026-04-04',NULL,'2026-04-15',4), -- NULL não entregou ainda 
('2026-04-05',NULL,'2026-04-16',2),
('2026-04-10','2026-04-19','2026-04-17',5)

SELECT * FROM EMPRESTIMO1

INSERT INTO EMPRESTIMO_LIVRO1(ID_LIVRO,ID_EMPRESTIMO) VALUES
(1,1),(2,1),(3,2),(4,3),(5,3),(1,4),(2,5)

SELECT * FROM EMPRESTIMO_LIVRO1

INSERT INTO MULTA1(VALOR,ID_EMPRESTIMO,DATA_PAGAMENTO) VALUES 
(15.00, 1,'2026-04-11'),-- atraso
(10.00, 3, NULL), -- não pagou ainda
(20.00, 5,'2026-04-14')

SELECT * FROM MULTA1

SELECT 
U.NOME, E.ID_EMPRESTIMO,E.DATA_EMPRETIMO,E.DATA_DEVOLUCAO
FROM EMPRESTIMO1 E
JOIN USUARIO1 U ON E.ID_USUARIO = U.ID_USUARIO;
--Mostra o nome do usuário junto com seus empréstimos


SELECT 
U.NOME,M.VALOR
FROM USUARIO1 U
JOIN EMPRESTIMO1 E ON U.ID_USUARIO = E.ID_USUARIO
JOIN MULTA1 M ON E.ID_EMPRESTIMO = M.ID_EMPRESTIMO;
--Mostra o nome dos usuários que possuem multa e o valor da multa.

SELECT 
E.ID_EMPRESTIMO, COUNT(EL.ID_LIVRO) AS QTD_LIVROS
FROM EMPRESTIMO1 E
JOIN EMPRESTIMO_LIVRO1 EL ON E.ID_EMPRESTIMO = EL.ID_EMPRESTIMO
GROUP BY E.ID_EMPRESTIMO;
--Ele mostra quantos livros tem em cada empréstimo